feat: :sparkles: add uploaderIcon
DEV-MUGLES/pickk-super-admin pull request #11
Opened 2020-12-17 09:56 UTC by syoung125

resolve #10

2020-12-17 10:02 UTC, syoung125 commented on src/types/UploaderType.ts
> +};
SelectsRequest.ts 파일보고 관련된 소스인것같아서 여기로 위치를 옮겨서
card에서 사용했어요

2020-12-17 10:02 UTC, syoung125 commented on src/components/selects-request/kanban-board/card.tsx
> +          </UploaderTypeIconContainer>
여기서 사용했는데, 
 {user.uploaderType} 값은 NONE인것을 확인해서 NONE일때 youtubeIcon이 나오도록 테스트해봤는데
 아이콘도 안뜨고 || <></>이부분에 || <>aaa</> 이런식으로 테스트 해보았는데도
 아이콘도 안뜨고 aaa도 안뜨는데 못고치겠어요

2020-12-17 10:15 UTC, syoung125 commented on src/components/selects-request/kanban-board/card.tsx
> +          </UploaderTypeIconContainer>
![image](https://user-images.githubusercontent.com/39763891/102474522-179a5c00-409c-11eb-913e-10ba444ad741.png)

콘솔창에 이렇게 떠요
Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.

2020-12-17 10:16 UTC, greatSumini commented on src/types/UploaderType.ts
> +};
아하 이 부분은
lib로 빼는게 좋을 것 같아요!
해당 기능이 type보단 함수처럼 작동하기 때문입니다.
이 함수만 lib/user 경로로 빼서 작성해주시면 됩니당

2020-12-17 10:19 UTC, greatSumini commented on src/components/selects-request/kanban-board/card.tsx
> +          </UploaderTypeIconContainer>
ReactElement와 React.FunctionComponent가 다르기 때문에 발생한 현상입니다
Component는 `<Sumin />`처럼 jsx 문법에 맞게 호출해주셔야 렌더링됩니다 ㅎㅎ
관련 정보 찾아보시면 좋을 것 같아요

2020-12-17 10:20 UTC, greatSumini commented on src/interfaces/User/IUser.ts
> +import { UploaderType } from '@src/types/uploaderType';
Git은 파일명의 대소문자변경을 감지하지 못 합니다! 특별한 과정을 거쳐서 바꿔줘야 하는데, 찾아보시면 좋을 것 같아용

2020-12-17 10:27 UTC, syoung125 commented on src/types/UploaderType.ts
> +};
넵 수정했습니다. 이부분은 맞게 작성한건가요??

2020-12-17 10:29 UTC, syoung125 commented on src/components/selects-request/kanban-board/card.tsx
> +          </UploaderTypeIconContainer>
<UploaderTypeIcon /> 이렇게 작성하면 빨간줄이 발생하거든요..ㅠㅠ 그리고 저렇게 작성한경우
UploaderTypeIcon[user.uploaderType] 이런식으로 이떻게 type을 알려줘야하는지 모르겠어요

2020-12-17 10:36 UTC, greatSumini commented on src/types/UploaderType.ts
> +};
음.. 아래처럼 바꿔서 사용하는게 좋을 것 같아요!
```suggestion
export const getUploaderTypeIconComponent = (uploaderType: UploaderType) => (
  {
    [None]: <YoutubeIcon />,    // 테스트 후 Youtuber로 변경해야 함
    [Instagramer]: <InstagramIcon />,
    [Blogger]: <BlogIcon />,
  }[uploaderType] || () => <></>
);
```

2020-12-18 01:06 UTC, greatSumini requested changes

2020-12-18 01:06 UTC, greatSumini commented on src/types/UploaderType.ts
> +
이 내용을 types/User 파일에 작성하는게 좋을 것 같아요

2020-12-18 01:06 UTC, greatSumini commented on src/lib/user/UploaderTypeIcon.tsx
> +  }[uploaderType] || <></>);
lib/User.ts 에 작성하면 될 것 같습니다

2020-12-18 01:06 UTC, greatSumini commented on src/assets/icons/BlogIcon.tsx
> +
1. 파일명은 되도록 kebab-case로 작성해주세요!
  Model, Interface와 관련있는 경우에만 PascalCase를 사용합니다. (ex: User, Post)
2. directory path에 icon이라는 단어가 포함되어 있으니 파일명에선 생략해도 될 것 같아용
  BlogIcon.tsx -> blog.tsx
3. 업로더타입아이콘들끼리 같은 폴더에 묶으면 좋을 것 같아요!
  src/assets/icons/user/uploader-type/blog.tsx

2020-12-18 02:09 UTC, syoung125 commented on src/assets/icons/BlogIcon.tsx
> +
23c5593

2020-12-18 02:09 UTC, syoung125 commented on src/lib/user/UploaderTypeIcon.tsx
> +  }[uploaderType] || <></>);
71ff257

2020-12-18 02:10 UTC, syoung125 commented on src/types/UploaderType.ts
> +
71ff257

2020-12-18 04:48 UTC, syoung125 commented on src/types/UploaderType.ts
> +
21d497b

2020-12-18 05:00 UTC, greatSumini commented on src/components/selects-request/detail-drawer-content/index.tsx
> +      <DrawerApplicantSection {...user} snsLink={snsLink} uploaderType={user.uploaderType}/>
```suggestion
      <DrawerApplicantSection {...user} snsLink={snsLink} />
```

 JSX Spread Attributes 읽어보세요! [링크](https://gist.github.com/sebmarkbage/07bbe37bc42b6d4aef81)

2020-12-18 05:01 UTC, greatSumini approved these changes

2020-12-18 05:02 UTC, syoung125 commented on src/components/selects-request/detail-drawer-content/index.tsx
> +      <DrawerApplicantSection {...user} snsLink={snsLink} uploaderType={user.uploaderType}/>
4fcd357

2020-12-18 05:03 UTC, merged