feat: :sparkles: add selects-request archive table
DEV-MUGLES/pickk-super-admin pull request #13
Opened 2020-12-18 10:20 UTC by syoung125

resolve #12

<img width="1440" alt="스크린샷 2020-12-18 오후 7 10 41" src="https://user-images.githubusercontent.com/39763891/102603194-d1113400-4165-11eb-8ae2-f5429756de42.png">

- antd 디자인 적용이 좀 느리게 되었었는데 지금은 좀만이 기다린 것 같은데도 적용이 안돼요
- test data 부분은 마지막에 지울 예정입니다!

2020-12-18 10:26 UTC, pickk-dev commented
#### 📝Changed routes:


| [**…elects-request/archive**](https://pickk-super-ad-git-feature-12add-selects-request-archive-268606.dev-mugles.vercel.app/manage/selects-request/archive) |
|:-:|
|<a href="https://pickk-super-ad-git-feature-12add-selects-request-archive-268606.dev-mugles.vercel.app/manage/selects-request/archive"><img src="https://images.weserv.nl?url=https://s.microlink.io/vbzTlv7iwlFz998oKcYjZ2blCZE_.png&w=600" alt="Screenshot of /manage/selects-request/archive" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/x9bPLjr10tPtUaVJC0mwmq_uUMM_.png">(view full size)</a> |







Commit cabbbe42ec137efd0f2c19d38834e2c46e7edb4a (https://pickk-super-ad-git-feature-12add-selects-request-archive-268606.dev-mugles.vercel.app).

2020-12-18 10:59 UTC, greatSumini requested changes
잘 구현해주셨네요 ㅎㅎ 수고하셨습니다
전체적으로 아쉬운 부분이 크게 두가지 있는데요
1. 타입스크립트 활용. 특히 컴포넌트 타이핑!
2. import 순서, 사용 안 한 변수 등 디테일.

커밋하실 때 코드를 한번 다시 읽으면서 점검해보시면 좋을 것 같아요!
타입스크립트는 조금씩 연습해보시면 될 것 같습니다 ㅎㅎ

2020-12-18 10:59 UTC, greatSumini commented on src/components/selects-request/archive-list/table/colums.tsx
> +import { getUploaderTypeIconComponent } from '@src/lib/User';
```suggestion
import { P } from '@src/component/atoms';

import { getUploaderTypeIconComponent } from '@src/lib/User';
import { SelectsRequestStatusToKor } from '@src/types';
```

import문 줄바꿈/순서 변경해야합니다~

2020-12-18 10:59 UTC, greatSumini commented on src/components/selects-request/archive-list/table/colums.tsx
> +  return <P>{`${moment(text).format('YYYY.MM.DD HH:MM')}`}</P>;
```suggestion
  return <P>{moment(text).format('YYYY.MM.DD HH:MM')}</P>;
```

변수값을 그대로 쓸땐 template literal로 만들지 않아도 됩니다!

2020-12-18 10:59 UTC, greatSumini commented on src/components/selects-request/archive-list/table/index.tsx
> +  }
```suggestion
  if (!dataSource) {
    console.log(dataSource);
    return null;
  }
```

null일때도 대응되도록 위와 같이 변경해도 좋을 것 같아요

2020-12-18 10:59 UTC, greatSumini commented on src/components/selects-request/archive-list/table/index.tsx
> +import { HEADER_HEIGHT } from '@src/component/organisms/g-header';
이 변수를 사용하지 않고 있습니다.

2020-12-18 10:59 UTC, greatSumini commented on src/components/selects-request/archive-list/index.tsx
> +`;
현재 Wrapper 컴포넌트의 children이 table뿐이어서 element 존재 의미가 없습니다!

2020-12-18 10:59 UTC, greatSumini commented on src/components/selects-request/archive-list/index.tsx
> +    </Wrapper>
```suggestion
  const mapTableData = (data) => {
    return {
      ...data,
      userName: data.user.name,
      userUploaderType: data.user.uploaderType,
      itemBrandName: data.item.brandName,
      itemName: data.item.name,
      option: data.product.options.join('/'),
      assigneeName: data.assignee.name,
    };
  }

  return (
    <Wrapper>
      <ArchiveTable
        dataSource={items}
        columns={columns}
        dataMapper={mapTableData}
      />
    </Wrapper>
```

1. 인라인 함수 사용을 지양해주세요!
2. colums -> columns 오타 수정했습니다.
3. 변수 네이밍의 통일성을 유지하면 좋을 것 같아요.
  user.name -> userName
  user.uploaderType -> userUploaderType 이므로
  item.brandName -> itemBrandName
  item.name -> itemName
  assignee.name -> assigneeName 으로 변경하면 좋을 것 같습니다!
4. data parameter를 타이핑 해보세요!

2020-12-18 10:59 UTC, greatSumini commented on src/components/selects-request/archive-list/index.tsx
> +import { colums } from './table/colums';
노션 참고해서 import 순서 바꿔보세요!

2020-12-18 10:59 UTC, greatSumini commented on src/components/selects-request/archive-list/index.tsx
> +  const { data: items, mutate, response } = useSelectsRequestList({
불필요한 코드는 push되면 안 됩니다!
사용 안 하는 변수는 지워주세용

2020-12-18 10:59 UTC, greatSumini commented on src/components/selects-request/archive-list/table/colums.tsx
> +  return <P>{`${moment(text).format('YYYY.MM.DD HH:MM')}`}</P>;
컴포넌트 선언해주신 센스 좋네요 👍🏻

2020-12-18 11:33 UTC, syoung125 commented on src/components/selects-request/archive-list/index.tsx
> +`;
9a61072

2020-12-18 11:34 UTC, syoung125 commented on src/components/selects-request/archive-list/table/colums.tsx
> +import { getUploaderTypeIconComponent } from '@src/lib/User';
9215a4e

2020-12-18 11:34 UTC, syoung125 commented on src/components/selects-request/archive-list/table/colums.tsx
> +  return <P>{`${moment(text).format('YYYY.MM.DD HH:MM')}`}</P>;
eea6961

2020-12-18 11:35 UTC, syoung125 commented on src/components/selects-request/archive-list/table/index.tsx
> +  }
3cea873

2020-12-18 11:35 UTC, syoung125 commented on src/components/selects-request/archive-list/index.tsx
> +    </Wrapper>
538b767

2020-12-18 11:36 UTC, syoung125 commented on src/components/selects-request/archive-list/index.tsx
> +import { colums } from './table/colums';
745a774

2020-12-18 11:36 UTC, syoung125 commented on src/components/selects-request/archive-list/table/index.tsx
> +import { HEADER_HEIGHT } from '@src/component/organisms/g-header';
af5f82d

2020-12-21 01:28 UTC, syoung125 commented on src/components/selects-request/archive-list/index.tsx
> +  const { data: items, mutate, response } = useSelectsRequestList({
538b767

2020-12-21 01:36 UTC, merged