feat: :sparkles: add login page
DEV-MUGLES/pickk-super-admin pull request #2
Opened 2020-12-04 07:13 UTC by YYOngYYong

2020-12-04 07:38 UTC, greatSumini requested changes
수고하셨습니다 ㅎ

2020-12-04 07:38 UTC, greatSumini commented on pages/login.tsx
> +import { Space } from '@src/components/atoms';
```suggestion
import LoginForm from '@src/components/organisms/LoginForm';
import LogoIcon from '@src/assets/icon/logo';
import { Space } from '@src/components/atoms';
```

2020-12-04 07:38 UTC, greatSumini commented on pages/login.tsx
> +      <StyledContent>
현재 불필요한 구조라서 1중으로 줄여주세용

2020-12-04 07:38 UTC, greatSumini commented on src/components/organisms/LoginForm.tsx
> +import { Space } from '../atoms';
```suggestion
import { AuthService } from '@src/services';
import React, { useState } from 'react';
import styled from 'styled-components';
import { Space } from '@src/component/atoms';
```

1. import문 정리해주세요!
2. 다른 모듈 참조할 때 최대한 절대경로 사용해주세요~
3. atoms/Space 대신 margin, padding을 사용해보세요~

2020-12-04 07:38 UTC, greatSumini commented on src/components/organisms/LoginForm.tsx
> +      alert('한글 입력은 지원하지 않습니다. 영문으로 전환해주세요.');
```suggestion
      alert('한글 입력은 지원하지 않습니다. 영문으로 전환해주세요.');
```

pickk-admin에서 한 방식으로 적용해주세용 `message.warning?`으로 바꿔주세요

2020-12-04 07:38 UTC, greatSumini commented on src/components/organisms/LoginForm.tsx
> +    setLoginFormState({ ...loginFormState, [e.target.name]: e.target.value });
```suggestion
  const handleLoginFormChange = (e) => {
    const {name, value} = e.target;
  
    if (/[ㄱ-ㅎ|ㅏ-ㅣ|가-힣]/.test(value)) {
      alert('한글 입력은 지원하지 않습니다. 영문으로 전환해주세요.');
      focus;
      return;
    }
    setLoginFormState({ ...loginFormState, [name]: value });
```

destructuring을 적용할 수 있는 곳엔 최대한 적용해주세요!

2020-12-04 07:38 UTC, greatSumini commented on src/components/organisms/LoginForm.tsx
> +  const handleLogin = async () => {
여기도 destructuring을 적용해볼 수 있겠죠?

2020-12-04 07:38 UTC, greatSumini commented on src/components/organisms/LoginForm.tsx
> +    }
```suggestion
// 함수 외부
const isValidForm = loginFormState.email !== '' || loginFormState.password !== '';
...

// 함수 내부
    if (!isValidForm) {
      alert('아이디/비밀번호를 확인해주세요');
      return;
    }
    
    try { 
      await AuthService.superToken(
        loginFormState.email,
        loginFormState.password
      );
      alert('로그인 성공');
    } catch (e) {
      alert('로그인에 실패했습니다' + e);
    }
```

1. 함수를 분리해서 각 함수의 몸통을 줄여보세요.
2. escape case를 다룰땐 return 시켜버리기, 되도록 함수 몸통의 맨 윗부분에 작성하기
3. try-catch 잘 활용하기

2020-12-04 07:38 UTC, greatSumini commented on src/components/organisms/LoginForm.tsx
> +  return (
```suggestion
  };
  
  return (
```

2020-12-04 09:14 UTC, YYOngYYong commented on pages/login.tsx
> +import { Space } from '@src/components/atoms';
9ba9232

2020-12-04 09:15 UTC, pickk-dev commented
#### 📝Changed routes:


| [**/**](https://pickk-super-admin-git-feature-1add-loginpage.pickk-dev.vercel.app/) | [**/login**](https://pickk-super-admin-git-feature-1add-loginpage.pickk-dev.vercel.app/login) |
|:-:|:-:|
|<a href="https://pickk-super-admin-git-feature-1add-loginpage.pickk-dev.vercel.app/"><img src="https://images.weserv.nl?url=https://s.microlink.io/T5g_JfDT3Cl_NPheAAQqoRM1Z0U_.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/NONi9IzVuVLd9xvcarzap3vnnDA_.png">(view full size)</a> |<a href="https://pickk-super-admin-git-feature-1add-loginpage.pickk-dev.vercel.app/login"><img src="https://images.weserv.nl?url=https://s.microlink.io/5XEeBsyJTNLQsUlULOmB4ITALI0_.png&w=600" alt="Screenshot of /login" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/aDtdwAEjABY8EPi8Tjw2Z7jhdFM_.png">(view full size)</a> |







Commit 3bfd441722f0bdc9bfc9b1e6c9adf891392387a8 (https://pickk-super-admin-git-feature-1add-loginpage.pickk-dev.vercel.app).

2020-12-05 08:43 UTC, YYOngYYong commented on pages/login.tsx
> +      <StyledContent>
9ba9232

2020-12-05 09:00 UTC, YYOngYYong commented on src/components/organisms/LoginForm.tsx
> +import { Space } from '../atoms';
3bfd441

2020-12-05 09:01 UTC, YYOngYYong commented on src/components/organisms/LoginForm.tsx
> +import { Space } from '../atoms';
e3bb001

2020-12-05 09:57 UTC, YYOngYYong commented on src/components/organisms/LoginForm.tsx
> +    setLoginFormState({ ...loginFormState, [e.target.name]: e.target.value });
bd7c002

2020-12-05 10:52 UTC, YYOngYYong commented on src/components/organisms/LoginForm.tsx
> +    }
8f0bd28

2020-12-06 12:15 UTC, YYOngYYong commented on src/components/organisms/LoginForm.tsx
> +      alert('한글 입력은 지원하지 않습니다. 영문으로 전환해주세요.');
eb315fe

2020-12-07 01:56 UTC, merged