Feature/20/add look list page,components
DEV-MUGLES/pickk-super-admin pull request #21
Opened 2020-12-22 07:56 UTC by syoung125

![image](https://user-images.githubusercontent.com/39763891/102863420-e9d75d80-4475-11eb-9d33-fa805f121291.png)

구현결과입니다.

1. 표에서 아이템들의 수직 정렬이 아래로 가는데 그 이유를 모르겠습니다
2. 스타일 태그의 기능은 아직 작동하지 않고, 태그로 선택되어 있으면 검정색으로 보여지도록은 구현했습니다. 
(이 부분 코드를 map으로 조금 비효율적으로 구현한 느낌이라서 한번 리뷰 받고 하려고 합니다!)
3. 아 그리고 useLookList에 넘겨주는 params에서 limit와 offset 값은 제가 태그가 부여된 룩을 찾으려고 임의로 부여하였는데, 디폴트 값은 어떻게 되나요??

2020-12-22 08:13 UTC, greatSumini requested changes
1. 표에서 아이템들의 수직 정렬이 아래로 가는데 그 이유를 모르겠습니다
2. 스타일 태그의 기능은 아직 작동하지 않고, 태그로 선택되어 있으면 검정색으로 보여지도록은 구현했습니다.
(이 부분 코드를 map으로 조금 비효율적으로 구현한 느낌이라서 한번 리뷰 받고 하려고 합니다!)
3. 아 그리고 useLookList에 넘겨주는 params에서 limit와 offset 값은 제가 태그가 부여된 룩을 찾으려고 임의로 부여하였는데, 디폴트 값은 어떻게 되나요??
4. yarn test 했을 때 다음과 같은 오류가 나는데요
image
import styleTagsData from '@src/data/style-tags';
이렇게 임포트 하는게 아닌 것인가요??


1 : 개발자 도구로 Element들의 CSS를 분석해보세요!
2, 3, 4 : 리뷰 남겼습니다~

2020-12-22 08:13 UTC, greatSumini commented on src/components/look/look-list/table/style-tag-list/index.tsx
> +const StyleTagList = ({ styleTags }: StyleTagListProps) => {
```suggestion
function StyleTagList({ styleTags }: StyleTagListProps) {
```

컴포넌트는 function으로 선언합니다. React 컴포넌트 작성요령 노션 문서 확인해주세용

2020-12-22 08:13 UTC, greatSumini commented on src/components/look/look-list/table/style-tag-list/index.tsx
> +            type={isChecked(tag) ? 'primary' : 'line'}
```suggestion
            type={styleTags.find(styleTag => styleTag.id === tag.id) ? 'primary' : 'line'}
```

위와 같이 리팩토링 할 수 있습니다.

2020-12-22 08:13 UTC, greatSumini commented on src/components/look/look-list/index.tsx
> +      styleTags: styleTags,
이렇게 작성하신 이유가 있나요??

2020-12-22 08:13 UTC, greatSumini commented on src/components/look/look-list/index.tsx
> +      },
```suggestion
      render: (_, {styleTags}: ILook) =>  <StyleTagList styleTags={styleTags} />,
```

이렇게 바꿔볼 수 있습니다.

2020-12-22 08:51 UTC, syoung125 commented on src/components/look/look-list/index.tsx
> +      styleTags: styleTags,
이부분은 data. 여러번 쓰는 것보다 이렇게 사용하는 것이 더 깔끔해 보여서 작성했는데요
organism 모듈 분리 생각하다보니 dataMapper에 타입을 지정하는 것이 확장성면에서 안좋은 것같아서 원래 코드로돌렸습니다ㅎㅎ

2020-12-22 09:53 UTC, syoung125 commented on src/components/look/look-list/table/style-tag-list/index.tsx
> +import styleTagsData from '@src/data/style-tags';
2df452c

2020-12-22 09:53 UTC, syoung125 commented on src/components/look/look-list/table/style-tag-list/index.tsx
> +const StyleTagList = ({ styleTags }: StyleTagListProps) => {
686ca00

2020-12-22 09:53 UTC, syoung125 commented on src/components/look/look-list/table/style-tag-list/index.tsx
> +            type={isChecked(tag) ? 'primary' : 'line'}
0708ea9

2020-12-22 09:54 UTC, syoung125 commented on src/components/look/look-list/table/style-tag-list/index.tsx
> +import styleTagsData from '@src/data/style-tags';
1번; 
411c7b0

2020-12-22 09:54 UTC, pickk-dev commented
#### 📝Changed routes:


| [**/manage/look**](https://pickk-super-admin-git-feature-20add-look-list-pagecomponents.dev-mugles.vercel.app/manage/look) |
|:-:|
|<a href="https://pickk-super-admin-git-feature-20add-look-list-pagecomponents.dev-mugles.vercel.app/manage/look"><img src="https://images.weserv.nl?url=https://s.microlink.io/_it4MrP73HwQ3CAerqshvMLuBr8_.png&w=600" alt="Screenshot of /manage/look" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/kYQ_vnsXQLQJ_cZjCc_mf_73xnU_.png">(view full size)</a> |







Commit 90db87376b32174c3f28386455a15d384da08c17 (https://pickk-super-admin-git-feature-20add-look-list-pagecomponents.dev-mugles.vercel.app).

2020-12-22 09:58 UTC, syoung125 commented on src/components/look/look-list/index.tsx
> +      },
90db873

2020-12-22 09:58 UTC, syoung125 commented on src/components/look/look-list/index.tsx
> +      styleTags: styleTags,
90db873

2020-12-22 09:58 UTC, syoung125 commented on src/components/look/look-list/table/index.tsx
> +export default LookTable;
90db873

2020-12-22 10:05 UTC, syoung125 commented on src/components/look/look-list/table/index.tsx
> +export default LookTable;
넵! 모듈로 분리하였으니까 look-list와 archive-list 하위 폴더인 table을 지우는 것이 더 나은 구조일까요??

2020-12-22 10:06 UTC, syoung125 commented on src/components/look/look-list/index.tsx
> +      },
90db873

2020-12-22 10:06 UTC, syoung125 commented on src/components/look/look-list/table/index.tsx
> +export default LookTable;
90db873

2020-12-22 13:43 UTC, greatSumini commented on src/components/look/look-list/table/index.tsx
> +export default LookTable;
넵 ㅎㅎ 그런데 atom 보단 molecule 또는 organism이 맞는 것 같아요!

2020-12-22 13:44 UTC, greatSumini commented on src/components/look/look-list/index.tsx
> +      styleTags: styleTags,
아하 아뇹 앞에서 ...data를 해줬기 때문에 styleTags: data.styleTags는 생략해도 되는 코드인 것 같은데, 적어주신 이유가 있나요??

2020-12-23 01:20 UTC, syoung125 commented on src/components/look/look-list/index.tsx
> +      styleTags: styleTags,
아하! 그러게요! 그 부분은 지워도 될것같아요

2020-12-23 02:22 UTC, syoung125 commented on src/components/look/look-list/index.tsx
> +      styleTags: styleTags,
a500335

2020-12-23 02:22 UTC, syoung125 commented on src/components/look/look-list/table/index.tsx
> +export default LookTable;
a500335

2020-12-23 02:25 UTC, syoung125 commented
1. 스타일 태그 체크하는 것은 구현 했는데 저장 클릭 시 403에러가 나옵니다ㅠ
2. yarn test 시에는 에러가 발생하지 않았는데, push 하니까 `import styleTagsData from '@src/data/style-tags.json';` 요부분에서 오류가 나요!

2020-12-23 02:46 UTC, greatSumini requested changes

2020-12-23 02:46 UTC, greatSumini commented on src/components/look/look-list/style-tag-list/index.tsx
> +    await LookService.partialUpdate(id, { styleTags: tags });
```suggestion
    await LookService.partialUpdate(id, { styleTagIds: selectedTagIds });
```

nested object를 update할땐 Foreign key를 업데이트해주세용

2020-12-23 02:46 UTC, greatSumini commented on src/components/look/look-list/style-tag-list/index.tsx
> +  const [tags, setTags] = useState<StyleTag[]>([...styleTags]);
```suggestion
  const [selectedTagIds, setSelectedTagIds] = useState<number[]>(styleTags.map(styleTag => styleTag.id));
```

1. 변수 이름 명확하게 변경
2. 저장해야하는 정보만 저장! (전체가 아닌 id만)

2020-12-23 02:46 UTC, greatSumini commented on src/components/look/look-list/style-tag-list/index.tsx
> +import { LookService } from '@src/services';
```suggestion
import { StyleTag } from '@src/types';
import { LookService } from '@src/services';

import STYLE_TAGS from '@src/data/style-tags.json';
```

상수 변수는 대문자 스네이크 케이스로 작성해주세요!
import문은 분리해서 가장 아래에 작성해주세요

2020-12-23 02:46 UTC, greatSumini commented on src/components/look/look-list/style-tag-list/index.tsx
> +  };
1. 가독성 높이기
  built in 함수들을 적절히 사용해 가독성을 높일 수 있습니다. (Array.prototype.includes, concat)
2. 중복 로직 없애기
  setTags 함수 호출이 불필요하게 중복됩니다! 중복을 최대한 제거해주시는게 좋습니다.

```suggestion
  const handleCheck = (id: number) => {
    const isSelected = selectedTagIds.includes(id);
    setSelectedTagids(selectedTagIds.concat(isSelected ? [] : id));
  };
```

2020-12-23 02:46 UTC, greatSumini commented on src/components/look/look-list/style-tag-list/index.tsx
> +          />
```suggestion
        {STYLE_TAGS.map((styleTag: StyleTag) => (
          <Button
            key={styleTag.id}
            title={styleTag.name}
            onClick={() => handleCheck(styleTag.id)}
            type={selectedTagIds.includes(styleTag.id) ? 'primary' : 'line'}
            size="small"
            radius="round"
          />
```

1. 위 변경점 적용 + 가독성!
2. 배열변수는 복수형으로 네이밍하고, map했을 땐 복수형->단수형으로만 변환합니다!
3. 인라인 스타일을 styled-component로 대체해주세요~

2020-12-23 02:46 UTC, greatSumini commented on src/components/look/look-list/style-tag-list/index.tsx
> +        onClick={() => handleSave()}
```suggestion
        onClick={handleSave}
```

이렇게 넘겨주는거랑 같습니당

2020-12-23 02:46 UTC, greatSumini commented on src/components/look/look-list/style-tag-list/index.tsx
> +        style={{ margin: '1.2rem auto', padding: '0.2rem 2rem' }}
```suggestion
        style={{ margin: '1.2rem auto', padding: '0.2rem 2rem' }}
```

styled-component로 대체해봐요!

2020-12-23 02:52 UTC, syoung125 commented on src/components/look/look-list/style-tag-list/index.tsx
> +    await LookService.partialUpdate(id, { styleTags: tags });
앗 그럼 id가 Foreign key가 되어야한단 말씀이신가용? 잘 이해가 되지않았어요..ㅠㅠ!

2020-12-23 02:54 UTC, syoung125 commented on src/components/look/look-list/style-tag-list/index.tsx
> +  const [tags, setTags] = useState<StyleTag[]>([...styleTags]);
오 마자요 이렇게 하고 싶었는데 문법을 몰랐어요ㅠㅠ! 자스 공부좀 해야겠네여ㅎㅎㅎ

2020-12-23 03:03 UTC, greatSumini commented on src/components/look/look-list/style-tag-list/index.tsx
> +    await LookService.partialUpdate(id, { styleTags: tags });
예를 들어 어떤 포스트의 작성자를 변경하고 싶으면,
partialUpdate할 때 user object 전체 대신 userId만 변경할 유저의 id로(Foreign key) 넘겨주면 됩니다!

2020-12-23 03:12 UTC, syoung125 commented on src/components/look/look-list/style-tag-list/index.tsx
> +  };
엇 그런데 이렇게 변경하면 체크 isSelected가 ture 일때 selectedTagIds에서 id를 제거하지 않아 체크 해제가 안되는데, 이건 어떻게 해결하나요??

2020-12-23 03:15 UTC, greatSumini commented on src/components/look/look-list/style-tag-list/index.tsx
> +  };
```suggestion
  const handleCheck = (id: number) => {
    const isSelected = selectedTagIds.includes(id);
    setSelectedTagids(
      selectedTagIds.filter(selectedTagId => selectedTagId != id).concat(isSelected ? [] : id)
    );
  };
```

앗 제가 실수했네요.
먼저 filter하고 concat해주시면 됩니다!

2020-12-23 03:39 UTC, syoung125 commented on src/components/look/look-list/style-tag-list/index.tsx
> +  };
d3d4728

2020-12-23 03:39 UTC, syoung125 commented on src/components/look/look-list/style-tag-list/index.tsx
> +import { LookService } from '@src/services';
f512ca2

2020-12-23 03:40 UTC, syoung125 commented on src/components/look/look-list/style-tag-list/index.tsx
> +        style={{ margin: '1.2rem auto', padding: '0.2rem 2rem' }}
66d0864

2020-12-23 03:40 UTC, syoung125 commented on src/components/look/look-list/style-tag-list/index.tsx
> +        onClick={() => handleSave()}
66d0864

2020-12-23 03:40 UTC, syoung125 commented on src/components/look/look-list/style-tag-list/index.tsx
> +          />
66d0864

2020-12-23 03:40 UTC, syoung125 commented on src/components/look/look-list/style-tag-list/index.tsx
> +    await LookService.partialUpdate(id, { styleTags: tags });
d3d4728

2020-12-23 03:42 UTC, syoung125 commented on src/components/look/look-list/style-tag-list/index.tsx
> +  const [tags, setTags] = useState<StyleTag[]>([...styleTags]);
d3d4728

2020-12-23 03:57 UTC, syoung125 commented on src/components/look/look-list/style-tag-list/index.tsx
> +  };
```js
const handleCheck = (id: number) => {
    const isSelected = selectedTagIds.includes(id);
    setSelectedTagIds(
      isSelected
        ? selectedTagIds.filter((selectedTagId) => selectedTagId !== id)
        : selectedTagIds.concat(id)
    );
  };
```
일단 이렇게 했습니다!

2020-12-23 06:34 UTC, greatSumini commented on src/components/look/look-list/style-tag-list/index.tsx
> +  };
filter가 반영이 안 됐네요 ㅠㅠ

2020-12-23 09:05 UTC, syoung125 commented on src/components/look/look-list/style-tag-list/index.tsx
> +    await LookService.partialUpdate(id, { styleTags: tags });
params type이 ILookUpdateDTO= Partial<ILookInputDTO>로 변경해주기전에는 빨간줄이 떴어서 저렇게 변경했는데요
그래도 403 에러가 나옵니다 ㅠㅠ 어떤 부분이 잘못된 것인지 모르겠습니다...!ㅜ

2020-12-23 09:13 UTC, greatSumini commented on src/components/look/look-list/style-tag-list/index.tsx
> +    await LookService.partialUpdate(id, { styleTagIds: selectedTagIds });
```suggestion
    try {
      await LookService.partialUpdate(id, { styleTagIds: selectedTagIds });
      message.success('성공적으로 저장되었습니다.');
    } catch (error) {
      message.success('실패했습니다.' + error?.message); 
    }
```

서버 관련 요청할 때는 try-catch 활용해서 에러핸들링 해주는 것도 좋습니다!

2020-12-23 09:14 UTC, syoung125 commented on src/components/look/look-list/style-tag-list/index.tsx
> +  };
2cdaa1f

2020-12-23 09:22 UTC, merged