Feature/35/add item tag page,components
DEV-MUGLES/pickk-super-admin pull request #36
Opened 2020-12-31 05:53 UTC by syoung125

* 해결 못한 문제점

1. 액션
* 상위분류 선택 시 하위분류 필드 초기화가 안된다
(대분류 선택 시 중분류와 태그의 antd Select value를 초기화해야하는데, 방법을 모르겠어서 이전 값이 남아있음)
* 태그 2개이상 선택 불가 기능을 [해당링크](https://codesandbox.io/s/happy-leftpad-lu84g?file=/index.js)를 참고해서 똑같이 구현했지만 동작 안됨 (selectedTagIds 배열에는 2개만 들어감)
* 액션 동작 시 아이템들에 해당 태그값이 부여되지만, 그 이후 아이템태그존재(hasItemTags)로 필터링 안됨 (false, true 일때 둘 다 그 아이템이 보임)
* 액션 적용 시 태그가 부여되지만 동시에 500 에러 발생
![image](https://user-images.githubusercontent.com/39763891/103396680-e6c82580-4b77-11eb-8eaf-e8db11156b6c.png)

2. 표에서 이미지가 큰 경우 이미지가 수축해서 보이는 것
![image](https://user-images.githubusercontent.com/39763891/103396657-c8622a00-4b77-11eb-936d-11274cd0bebc.png)

2020-12-31 06:40 UTC, pickk-dev commented
#### 📝Changed routes:


| [**/manage/item-tag**](https://pickk-super-admin-4pg7nw04w.vercel.app/manage/item-tag) |
|:-:|
|<a href="https://pickk-super-admin-4pg7nw04w.vercel.app/manage/item-tag"><img src="https://images.weserv.nl?url=https://s.microlink.io/C5UaHZRi1y8XmMV59Ksgd5o0qcg_.png&w=600" alt="Screenshot of /manage/item-tag" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/_5kQ7TAjNyDBWff9wzMzKnRuozU_.png">(view full size)</a> |







Commit f9ef3bc1e77afcc45200b2d556a29cd65064731e (https://pickk-super-admin-4pg7nw04w.vercel.app).

2020-12-31 07:29 UTC, greatSumini requested changes
고생하셨습니다! 리뷰 확인해주세용

2020-12-31 07:29 UTC, greatSumini commented on src/components/item-tag-manage/action/index.tsx
> +  );
거의 대부분의 경우에 마크업은 return문 안에서 모두 정의하는 것을 권장합니다!

2020-12-31 07:29 UTC, greatSumini commented on src/components/item-tag-manage/action/index.tsx
> +function Action({ onChangeAction }) {
```suggestion
function ItemTagManageAction({ onChangeAction }) {
```

1. 모든 변수의 이름에는 역할이 명확히 드러나야합니다.
2. prop typing이 안 되어있습니다 ㅠ

2020-12-31 07:29 UTC, greatSumini commented on src/component/organisms/spinner.tsx
> +function Spinner({
왜 이름이 Spinner인가요?

2020-12-31 07:29 UTC, greatSumini commented on src/components/item-tag-manage/filter/index.tsx
> +  });
1. 이 부분도 return문 안으로 옮겨주세요!
2. let 변수를 사용하지 않고 해결해보세요~

2020-12-31 07:29 UTC, greatSumini commented on src/components/item-tag-manage/index.tsx
> +  };
```suggestion
  const handleFilterChange = (input : any) => {
    setFilter({
      ...filter,
      ...input
    });
  };
```

1. 함수 네이밍은 영어의 어순을 따라주세요!
2. 위와 같이 parameter를 하나로 줄여보면 좋을 것 같아요

2020-12-31 07:29 UTC, greatSumini commented on src/components/item-tag-manage/index.tsx
> +  const handleChangeAction = async (
```suggestion
  const handleChangeActionSubmit = async (
```

1. 이벤트핸들러의 네이밍에는 핸들링하는 이벤트를 나타내는 동사가 포함됩니다! (ex: onClick, onFocus, onMouseEnter, ... )

2020-12-31 07:29 UTC, greatSumini commented on src/components/item-tag-manage/index.tsx
> +      <br />
margin, padding 등을 사용해서 해결해봐주세용

2020-12-31 07:29 UTC, greatSumini commented on src/services/Item/index.ts
> +  body: ItemActionRequestParams,
```suggestion
  body: ItemActionRequestParams,
```

type이름이 ItemActionRequestParams네요 ㅠㅠ 적절히 변경해주세요

2020-12-31 07:29 UTC, greatSumini commented on src/services/Item/index.ts
> +  Axios(actionConfig(ids, body, req)).then((res) => res.data);
```suggestion
  axios(actionConfig(ids, body, req)).then((res) => res.data);
```

다른 모든 코드에서 axios의 첫 글자를 소문자로 사용하고 있습니다.

2020-12-31 07:29 UTC, greatSumini commented on src/services/Item/index.ts
> +const action = async (
```suggestion
const action = async (
```

action은 이 기능에 대해 명확히 설명하지 못 하는 것 같아요.
tag라는 네이밍이 더 좋을 것 같아요.

2020-12-31 09:08 UTC, syoung125 commented on src/component/organisms/spinner.tsx
> +function Spinner({
어떻게 지어야 할까 고민하다가 안드로이드에서 이런 ui 이름이 Spinner라서  이렇게 지었는데
음ㅁㅁ 어떤 이름이 적절할까요??

2020-12-31 09:10 UTC, syoung125 commented on src/components/item-tag-manage/action/index.tsx
> +  );
12dc269

2020-12-31 09:10 UTC, syoung125 commented on src/components/item-tag-manage/filter/index.tsx
> +  });
12dc269

2020-12-31 09:11 UTC, syoung125 commented on src/components/item-tag-manage/index.tsx
> +  const handleChangeAction = async (
1820deb

2020-12-31 09:12 UTC, syoung125 commented on src/components/item-tag-manage/index.tsx
> +  };
1820deb

2020-12-31 09:12 UTC, syoung125 commented on src/components/item-tag-manage/action/index.tsx
> +function Action({ onChangeAction }) {
1820deb

2020-12-31 09:13 UTC, syoung125 commented on src/components/item-tag-manage/index.tsx
> +      <br />
13264b5

2020-12-31 09:13 UTC, syoung125 commented on src/services/Item/index.ts
> +const action = async (
e418508

2020-12-31 09:13 UTC, syoung125 commented on src/services/Item/index.ts
> +  Axios(actionConfig(ids, body, req)).then((res) => res.data);
e418508

2020-12-31 09:13 UTC, syoung125 commented on src/services/Item/index.ts
> +  body: ItemActionRequestParams,
e418508

2020-12-31 09:50 UTC, syoung125 commented on src/components/item-tag-manage/index.tsx
> +  const handleChangeAction = async (
2b05eb4

action click 핸들러를 ItemTagManageAction prop으로 넘겨주는 대신에 체크된 아이템 리스트를 넘겨주는 것으로 변경하였는데
괜찮은가요??

2021-01-04 06:46 UTC, syoung125 commented on src/component/organisms/spinner.tsx
> +function Spinner({
select로 변경했습니다

2021-01-05 01:39 UTC, merged